version: '2.1'
orbs:
  win: circleci/windows@4.1
jobs:
  build:
    executor:
      name: win/default
    steps:
      - checkout
      - run: choco install openssl
      - run: |
          dir C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\
          $Env:PATH += ";C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\"
          devenv.exe .\win32\libcoap.sln /Build "Release DLL" /Project libcoap /Project "coap-client"
      - run: type ".\win32\x64\Release DLL\libcoap.log"
      - store_artifacts:
          path: '.\win32\x64\Release DLL\coap-client.exe'
      - store_artifacts:
          path: 'C:\Program Files\OpenSSL-Win64\bin\libssl-1_1-x64.dll'
workflows:
  my-workflow:
    jobs:
      - build